import { Duffel } from '@duffel/api'; import { config } from '../config.js'; import type { Passenger } from '../types.js';
const duffel=new Duffel({token:config.DUFFEL_ACCESS_TOKEN});
async function staysCall<T>(operation:()=>Promise<T>):Promise<T>{try{return await operation()}catch(e){if(e instanceof Error&&e.message)throw e;throw new Error('Duffel Stays is not enabled for this account. Request Stays access in the Duffel dashboard.')}}
export async function searchStays(input:{latitude:number;longitude:number;checkInDate:string;checkOutDate:string;adults:number;rooms:number;stars?:number}){const r=await staysCall(()=>duffel.stays.search({location:{radius:10,geographic_coordinates:{latitude:input.latitude,longitude:input.longitude}},check_in_date:input.checkInDate,check_out_date:input.checkOutDate,rooms:input.rooms,guests:Array.from({length:input.adults},()=>({type:'adult' as const}))}));return r.data.results.filter(x=>!input.stars||x.accommodation.rating===null||x.accommodation.rating>=input.stars).slice(0,5).map(x=>({searchResultId:x.id,name:x.accommodation.name,stars:x.accommodation.rating,location:x.accommodation.location,amount:x.cheapest_rate_total_amount,currency:x.cheapest_rate_currency,expiresAt:x.expires_at}))}
export async function searchFlights(input:{origin:string;destination:string;departureDate:string;returnDate?:string;adults:number;cabin?:'economy'|'premium_economy'|'business'|'first'}){
 const slices=[{origin:input.origin.toUpperCase(),destination:input.destination.toUpperCase(),departure_date:input.departureDate,departure_time:null,arrival_time:null}];
 if(input.returnDate)slices.push({origin:input.destination.toUpperCase(),destination:input.origin.toUpperCase(),departure_date:input.returnDate,departure_time:null,arrival_time:null});
 const request=await duffel.offerRequests.create({slices,passengers:Array.from({length:input.adults},()=>({type:'adult' as const})),cabin_class:input.cabin??'economy',return_offers:true});
 return {passengerIds:request.data.passengers.map(p=>p.id),offers:(request.data.offers??[]).slice(0,100).map(o=>({id:o.id,amount:o.total_amount,currency:o.total_currency,airline:o.owner.name,expiresAt:o.expires_at,slices:o.slices.map(s=>({origin:s.origin.iata_code,destination:s.destination.iata_code,duration:s.duration,stops:Math.max(0,s.segments.length-1),departingAt:s.segments[0]?.departing_at,arrivingAt:s.segments.at(-1)?.arriving_at}))}))};
}
export async function revalidateFlight(offerId:string){const offer=(await duffel.offers.get(offerId)).data;if(new Date(offer.expires_at).getTime()<=Date.now())throw new Error('Selected flight offer has expired; please search again');return {id:offer.id,amount:offer.total_amount,currency:offer.total_currency,passengerIds:offer.passengers.map(p=>p.id),airline:offer.owner.name,expiresAt:offer.expires_at,slices:offer.slices.map(s=>({origin:s.origin.iata_code,destination:s.destination.iata_code,duration:s.duration,departingAt:s.segments[0]?.departing_at,arrivingAt:s.segments.at(-1)?.arriving_at}))}}
export async function getStayRates(searchResultId:string){const result=(await staysCall(()=>duffel.stays.searchResults.fetchAllRates(searchResultId))).data;return {searchResultId,name:result.accommodation.name,checkInDate:result.check_in_date,checkOutDate:result.check_out_date,rates:result.accommodation.rooms.flatMap(room=>room.rates.map(rate=>({rateId:rate.id,room:room.name,name:rate.name,boardType:rate.board_type,paymentType:rate.payment_type,amount:rate.total_amount,currency:rate.total_currency,dueAtProperty:rate.due_at_accommodation_amount,cancellationTimeline:rate.cancellation_timeline,conditions:rate.conditions,expiresAt:rate.expires_at,bookableWithBalance:rate.available_payment_methods.includes('balance')}))).filter(x=>x.bookableWithBalance).slice(0,10)}}
export async function quoteStay(rateId:string){const q=(await staysCall(()=>duffel.stays.quotes.create(rateId))).data;return {quoteId:q.id,name:q.accommodation.name,checkInDate:q.check_in_date,checkOutDate:q.check_out_date,amount:q.total_amount,currency:q.total_currency,dueAtProperty:q.due_at_accommodation_amount}}
export async function bookStay(input:{quoteId:string;passengers:Passenger[];bookingId:string}){const lead=input.passengers[0];if(!lead)throw new Error('A lead hotel guest is required');const booking=(await staysCall(()=>duffel.stays.bookings.create({quote_id:input.quoteId,guests:input.passengers.map(p=>({given_name:p.givenName,family_name:p.familyName})),email:lead.email,phone_number:lead.phoneNumber,metadata:{booking_id:input.bookingId}}))).data;return {id:booking.id,reference:booking.reference,status:booking.status}}
export async function cancelStay(bookingId:string){return staysCall(()=>duffel.stays.bookings.cancel(bookingId))}
export async function bookFlight(input:{offerId:string;passengerIds:string[];passengers:Passenger[];amount:string;currency:string}){
 const passengers=input.passengers.map((p,i)=>({id:input.passengerIds[i]!,given_name:p.givenName,family_name:p.familyName,born_on:p.bornOn,gender:p.gender,title:p.title,email:p.email,phone_number:p.phoneNumber,...(p.passport?{identity_documents:[{type:'passport' as const,unique_identifier:p.passport.uniqueIdentifier,expires_on:p.passport.expiresOn,issuing_country_code:p.passport.issuingCountryCode}]}:{})}));
 const order=await duffel.orders.create({type:'instant',selected_offers:[input.offerId],payments:[{type:'balance',amount:input.amount,currency:input.currency}],passengers});
 return {id:order.data.id,bookingReference:order.data.booking_reference};
}
export async function cancelFlight(orderId:string){const quote=await duffel.orderCancellations.create({order_id:orderId});return duffel.orderCancellations.confirm(quote.data.id)}
